Repository AY2324S1-CS2103T-W16-1/tp, pull requests merged in 2023-10, with the labels that each got.

#32 Adapt storage
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#39 Add note and delete note feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/NoteContent.java
  src/main/java/seedu/address/model/note/NoteTitle.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
Labels: priority.High

#41 List notes feature
  src/main/java/seedu/address/logic/commands/ListNoteCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#54 Update DG for Storage
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task

#60 Fix bug empty fields note
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/NoteContent.java
  src/main/java/seedu/address/model/note/NoteID.java
  src/main/java/seedu/address/model/note/NoteTitle.java
  src/main/java/seedu/address/model/person/ContactID.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/note/NoteContentTest.java
  src/test/java/seedu/address/model/note/NoteIdTest.java
  src/test/java/seedu/address/model/note/NoteTitleTest.java
Labels: type.Bug, priority.High
