Repository AY2324S1-CS2103T-W16-1/tp, pull requests merged in 2023-11, with the labels that each got.

#72 Fix assertion duplicate contacts
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug, priority.High

#76 Tag features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListNoteCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ListPersonCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListNoteCommandTest.java
Labels: priority.High

#83 Event bug fix
  src/main/java/seedu/address/model/event/UniqueEventList.java
Labels: priority.High

#85 Not allowing null in EventTime and fix the bug of deleting contact lead to ghost events
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ListEventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventTime.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/ListEventCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/event/EventTimeTest.java
Labels: type.Bug, priority.High

#151 Change equals and isSamePerson method
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#153 Date bugs
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High

#169 Improve UG, more coverage and misc improvements
  README.md
  docs/UserGuide.md
  docs/index.md
  docs/team/larrywang0701.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/event/EventInformation.java
  src/main/java/seedu/address/model/event/EventLocation.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventOverlapException.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/event/EventInformationTest.java
  src/test/java/seedu/address/model/event/EventLocationTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/model/event/exceptions/DuplicateEventExceptionTest.java
  src/test/java/seedu/address/model/event/exceptions/EventOverlapExceptionTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium
